### DISCUSSION TITLE
How to set smaller units than minutes or liters

### DISCUSSION THREAD

**Discussion by malocycling** [petergridge/Irrigation-V5#139] [Q&A] [answered]
Hello, 
I'm trying to set up this controller on a small-scale system on the balcony.
So far I would be able to set up everything as I was planning to.
Runtime or water volume however seems to be an issue. Time can only be selected in multiples of 1 minute or 1 liter. Which option am I missing to set this to a more granular value?

**Comment by petergridge** [comment, marked as answer]
Hi,

The system by default operates in minutes, the easiest way to make it operate as seconds would be to apply an [adjustment factor](https://github.com/petergridge/Irrigation-V5?tab=readme-ov-file#adjustment-sensor) of 0.0167 i.e. a 1/60 so each minute will be treated as a second. Or if you are using volume, a factor of .001 to convert to ml.

You can use a variation of the following to create a template sensor to support this.
```
template:
  - sensor:
    - name: Adjustment
      state: "{{ states('input_number.adjustment') }}"
      icon: mdi:knob
input_number:
  adjustment:
    step: .0001
    default: .0167
    icon: mdi:knob
```
