### ISSUE TITLE
Irrigation Dormancy Period?

### ISSUE THREAD

**Issue by Nunjafush** [petergridge/Irrigation-V5#101]
Hi Peter,

First of all, thanks for all your efforts in creating, improving and maintaining your Irrigation integration for HA.  It's fantastic! It does everything I needed an irrigation controller to do and was very easy to set up.  I'm in Australia, so being able to select specific days of the week to water on so as to conform with our water restriction rules was really helpful, too. 

As part of the water restrictions, a Winter sprinkler ban is enforced from 1 June to 31 August. I often forget to turn off my irrigation system until after the ban starts and then, when the ban finishes, forget to turn it back on again. So, I was wondering if it would be possible to add Dormancy From and Dormancy To date fields to a Program so that it could be automatically disabled for the sprinkler ban?

**Comment by petergridge** [comment]
Hi, I'm in Perth at the moment visiting family, so understand the issue. I am happy to investigate a solution. 

One immediate possibility is to create an automation to disable/enable the program.

**Comment by petergridge** [comment]
I have had a play and found this works.

1. Create a local calendar, https://www.home-assistant.io/integrations/calendar, I named mine 'local'
2. Add the 'Watering Season' entry with the desired start and end dates, using the calendar link in the sidebar
3. When testing the calendar does not refresh immediately so leave the start at least 15 minutes into the future.
4. Check that the 'enable_program' switch name is consistent with your implementation
```
alias: Calendar
description: ""
triggers:
  - trigger: calendar
    entity_id: calendar.local
    event: start
    offset: "0:0:0"
  - trigger: calendar
    entity_id: calendar.local
    event: end
    offset: "0:0:0"
mode: parallel
max: 10
conditions:
  - condition: template
    value_template: "{{ 'Watering Season' in trigger.calendar_event.summary }}"
actions:
  - if:
      - condition: template
        value_template: "{{ trigger.event == 'start' }}"
    then:
      - data: {}
        target:
          entity_id: switch.enable_program
        action: switch.turn_on
      - action: notify.persistent_notification
        metadata: {}
        data:
          message: Watering Season started
    else:
      - data: {}
        target:
          entity_id: switch.enable_program
        action: switch.turn_off
      - action: notify.persistent_notification
        metadata: {}
        data:
          message: Watering Season ended
```
