### ISSUE TITLE
Program Frequency via sensor has disappeared

### ISSUE THREAD

**Issue by ryjogo** [petergridge/Irrigation-V5#154]
Either i have mis-read the documentation, or something has happened?

I have created my frequency using OpenWeatherMapHistory using:

```{% set avgtemp = (forecast1max + forecast2max + forecast3max)/3 -%}
{% if avgtemp < 10 -%}
Off
{% elif avgtemp < 20 -%}
Mon, Fri
{% else -%}
Mon, Thu, Sat
{% endif -%}
```

Yet i cannot find where i should apply this sensor to? At least i do not see any option in my program?

![Image](https://github.com/user-attachments/assets/4fcdbe19-e2d8-41a9-b57a-08b27df80483)

**Comment by petergridge** [comment]
Hi, Sorry I deprecated that option in the latest version, I will look to add this back in a as an option in a future (soon) release

**Comment by ryjogo** [comment]
Thanks! Unless I guess this can be achieved in automation - but would be nice to have this back

**Comment by petergridge** [comment]
I did a quick test and an automation will work, you will need to create options on the program to specify the frequencies. Trigger, condition and option can be derived from the openweathermaphistory sensor.

Off would need to update the operate on the enable_program switch for you program/s

```
description: ""
mode: single
triggers: []
conditions: []
actions:
  - action: select.select_option
    metadata: {}
    data:
      option: Mon, Wed, Fri
    target:
      entity_id: select.frequency
```
