### ISSUE TITLE
how to manage "Runtime adjustment sensor" and "Rain binary sensor"

### ISSUE THREAD

**Issue by L0bit0** [petergridge/Irrigation-V5#170]
Hi first I am not sure if this is really an issue, a question or a request... :-)

I come from a previous version last year when I had to create multiple helpers to have it working.

This year (I only irrigate on summer) I want to keep using. 

I was able to migrate/adapt the programs I had, except for the Runtime adjustment and Rain binary sensor.

in previous version I created two helpers:

- **input_number.riego_watteringfactor** to change time depending on previous rain, temperature... (Runtime adjustment sensor)
- **input_boolean.riego_rain_factor** to disable program if it is raining (Rain binary sensor)

now I relaice there are similar (or same functionality) but entity types are different:

- Runtime adjustment is a sensor, not a Input_number
- Rain sensor is a binary sensro not a input boolean.

is this correct?

There is no way to "reuse" previous entities? i has some automations that manage these sensors automatically...

Also, I do not find an easy way to create as helpers, only way to create are from templates?

Thanks!

**Comment by petergridge** [comment]
Hi,

You can translate your 'inputs' to 'sensors' using templates I have a couple of examples below. I use this technique to build my test harness.

Cheers
Pete

```
input_number:
  adjustment:
    min: 0
    max: 2
    step: .1
    icon: mdi:knob

template:
  - binary_sensor:
      - name: Rain
        state: "{{ is_state('input_boolean.rain','on') }}"
        icon: mdi:weather-pouring
  - sensor:
    - name: Adjustment
      state: "{{ states('input_number.adjustment') }}"
      icon: mdi:knob
```
