### ISSUE TITLE
Allow use of `input_boolean` entities as `Rain sensor` and `Water source sensor`

### ISSUE THREAD

**Issue by paulius2k** [petergridge/Irrigation-V5#176]
I have logic in Node Red which decides if it is raining or not. Similarly I have logic in NR which decides if my well is full with water or not.
Node Red allows to turn_on or turn_off an `input_boolean` helper, which I'd like to use in the zone setup as `rain sensor` and `water source sensor`.

However, only `binary_sensors` are allowed in the zone setup. Unfortunately, AFAIK there is no way to change the state of a `binary_sensor` from Node Red.

Would it be difficult to allow `input_boolean` entities as Rain sensor and Water source sensor?

**Comment by petergridge** [comment]
I can do that for the next release.

You can also use a template sensor to change the type.

```
template:
  - binary_sensor:
      - name: Rain
        state: "{{ is_state('input_boolean.rain','on') }}"
        icon: mdi:weather-pouring
```
