### ISSUE TITLE
development proposal - start irrigation on event occurrence

### ISSUE THREAD

**Issue by Kejszijo** [petergridge/Irrigation-V5#180]
Hi,

I really like the program, it's easy to use. ;) I have a development suggestion. I would be happy if there was an option that, for example, if the irrigation is scheduled for 6 am, it would only start if an event occurs. for example, in my case, if there is no one in the garden :) This is a simple binary sensor that could be set to have a timeout. In automation, it looks like this:

```
actions:
  - choose:
      - conditions:
          - condition: state
            entity_id: binary_sensor.garden_presence
            state: "off"
        sequence:
          - action: start irrigation........
      - conditions:
          - condition: state
            entity_id: binary_sensor.garden_presence
            state: "on"
        sequence:
          - wait_for_trigger:
              - trigger: state
                entity_id:
                  - binary_sensor.garden_presence
                from: "on"
                to: "off"
            continue_on_timeout: false
            timeout:
              hours: 1
              minutes: 0
              seconds: 0
              milliseconds: 0
          - action: start irrigation....
```

The entity and the timeout time could be specified in the user interface. For example, in the advanced options. If no entity is specified, it is ignored. The timeout time could be set to 1 hour by default.

Best Regards,
