### ISSUE TITLE
Water switch never turns off

### ISSUE THREAD

**Issue by asafhas** [petergridge/Irrigation-V5#22]
Hello,

After upgrading to version 5.2.0 I've noticed that sometimes the water switch remains ON forever. Happens about 1 out of 10 times.
I've added a few debug prints and saw this:
- Function async_turn_on in irrigationzone.py is called and turns ON the water switch successfully.
- No flow sensor is configured.
- Going into wait-cycle loop: "while watertime > 0: seconds_run += 1"...
- Then the call to "if self.check_switch_state()" returns TRUE (meaning switch is OFF). Even though the switch was just turned ON 1 sec before.
- The program exists with "stop = True", but the switch remains ON forever.
- Even the call to "self.async_turn_off" at the end doesn't turn OFF the water switch.

Maybe there is a race-condition between when the switch is turned ON, and when you test if it's OFF.
There is a 1sec sleep between, maybe it's not enough?

Thank you.

**Comment by petergridge** [comment]
Hi @asafhas,

Can you provide me the config you have; How many programs and the settings, each zone's settings.
Just to clarify the issue:
The individual zones are turning on/off as expected but the program is still appearing as running once all zones have completed their cycles?

**Comment by petergridge** [comment]
Hi,

Can you also let me know the irrigation switches/device you are using, this may have an impact, I have local control of my switching, but if you have a cloud based solution or one that has high latency this may change how the system behaves.

**Comment by petergridge** [comment]
I think if this is a latency issue you can move the 'await asyncio.sleep(1)' to immediately before the 'self.check_switch_state()'. It will help giving an additional second for the status to update without impacting the refresh cycle.

I will update my repository, but if you do make the change let me know if it resolves the issue.

**Comment by petergridge** [comment]
I have made the change, V5.2.3 has been published as a Beta. Please let me know if this resolves the issue and I will make it the main release.

**Comment by petergridge** [comment]
I managed to create a dummy high latency switch, the behaviour of the program was very odd. I will have a new version, 5.2.4,  that handles the high latency issue on turn on and turn off more elegantly, and provide warning in the log if it is encountered.

I am handling latency of up to 10 seconds that should be ample for almost all situations, touch wood.

```
switch:
  - platform: template
    switches:
      dummy_1:
        friendly_name: Zone 1
        value_template: "{{ is_state('input_boolean.dummy_switch_1', 'on') }}"
        turn_on:
          - delay: '00:00:06'
          - service: input_boolean.turn_on
            entity_id: input_boolean.dummy_switch_1
        turn_off:
          - delay: '00:00:06'
          - service: input_boolean.turn_off
            entity_id: input_boolean.dummy_switch_1

input_boolean:
  dummy_switch_1:
```
