### ISSUE TITLE
Event program_turned_off is never call

### ISSUE THREAD

**Issue by Loic691** [petergridge/Irrigation-V5#61]
Hi  @petergridge 
Event **_irrigation_event_** is never call when programs stops.
I saw the log this morning on my mobile phone but I loose it.
I will send you this log for the next program cycle, not tomorrow because raining is announce on openwheathermaphistory ;-)
Probably in this week !

And thanks for all; This integration is working perfectly ;-)

My code 
```
alias: Auto - Jardin - Arrosage - Fin programme
description: ""
trigger:
  - platform: event
    event_type: irrigation_event
    event_data:
      action: program_turned_off
      scheduled: true
condition: []
action:
  - service: notify.telegram_loic
    metadata: {}
    data:
      title: Irrigation
      message: Fin programm Arrosage {{ trigger.event.data.device_id }}
mode: single
```
